### ISSUE TITLE
'flashforge_adventurer_3' calls async_forward_entry_setup for integration

### ISSUE THREAD

**Issue by Animizio** [modrzew/hass-flashforge-adventurer-3#19]
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:188
Erstmals aufgetreten: 09:39:18 (2 Vorkommnisse)
Zuletzt protokolliert: 09:39:18

Detected that custom integration 'flashforge_adventurer_3' calls async_forward_entry_setup for integration, flashforge_adventurer_3 with title: FlashForge Adventurer 3 and entry_id: 0932eb3d732abd1e286667a961630579, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/flashforge_adventurer_3/__init__.py, line 18: hass.async_create_task(, please create a bug report at https://github.com/modrzew/hass-flashforge-adventurer-3/issues
Detected that custom integration 'flashforge_adventurer_3' calls async_forward_entry_setup for integration, flashforge_adventurer_3 with title: FlashForge Adventurer 3 and entry_id: 0932eb3d732abd1e286667a961630579, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/flashforge_adventurer_3/__init__.py, line 21: hass.async_create_task(, please create a bug report at https://github.com/modrzew/hass-flashforge-adventurer-3/issues

**Comment by dahlb** [comment]
[this pr could resolve this ticket](https://github.com/modrzew/hass-flashforge-adventurer-3/pull/20)

**Comment by EarlCrane** [comment]
Same issue just popped up
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/flashforge_adventurer_3/__init__.py", line 19, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, 'sensor')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by geir55** [comment]
Same here
Logger: homeassistant.config_entries
Kilde: config_entries.py:749
Første forekomst: 10:24:59 (1 occurrence)
Sist logget: 10:24:59

Error setting up entry FlashForge Adventurer 3 for flashforge_adventurer_3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/flashforge_adventurer_3/__init__.py", line 19, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, 'sensor')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by nikor30** [comment]
Same same

Logger: homeassistant.config_entries
Quelle: config_entries.py:749
Erstmals aufgetreten: 09:55:01 (5 Vorkommnisse)
Zuletzt protokolliert: 09:56:50

Error setting up entry FlashForge Adventurer 3 for flashforge_adventurer_3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/flashforge_adventurer_3/__init__.py", line 19, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, 'sensor')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
